sudo: required
services:
  - docker

before_install:
  - docker build -t anveshreddy4/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run -e CI=true anveshreddy4/react-test npm test
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

after_success:
  - docker build -t anveshreddy4/multi-client ./client
  - docker build -t anveshreddy4/multi-nginx ./nginx
  - docker build -t anveshreddy4/multi-server ./server
  - docker build -t anveshreddy4/multi-worker ./worker

# Take those images and push them to docker hub
  - docker push anveshreddy4/multi-client
  - docker push anveshreddy4/multi-nginx
  - docker push anveshreddy4/multi-server
  - docker push anveshreddy4/multi-worker
